from mysql.connector import Error
from FabiaNatura_functions import conectar_base_datos
